### ISSUE TITLE
Props

### ISSUE THREAD

**Issue by rogueturnip** [Eugnis/react-native-timeline-flatlist#1]
Thanks for doing this port to FlatList.

I'm noticing that most of the props don't seem to work as they do with the old version.  On IOS I'm not able to get the circles to render or the divider lines.

**Comment by alz10** [comment]
same here

**Comment by ahmad6242** [comment]
renderFooter
onEndReached
also not working !!!!
Someone have the solution for that...?

**Comment by Eugnis** [comment]
Updated with fix for props. Please check new version
