### ISSUE TITLE
Use TimeLine inside Scrollview

### ISSUE THREAD

**Issue by ozankonur** [Eugnis/react-native-timeline-flatlist#12]
How can I use TimeLine in a scrollview ? I would like to scroll hole page including TimeLine but I am getting "virtualized lists should never be nested inside plain scrollviews with the same orientation" warning and TimeLine not scrolling anymore..

**Comment by Jempan** [comment]
@ozankonur How did you solve this? I am having the same problem.

**Comment by Jempan** [comment]
> @ozankonur How did you solve this? I am having the same problem.

I found the solution, if anyone else is looking for it you can use options to set ListHeaderComponent:

`options={{
              ListHeaderComponent: this.renderHeader
            }}`

**Comment by ozankonur** [comment]
I just added "nestedScrollEnabled={true}" to my scrollview and my timeline.. You can add your timeline like this:
` <Timeline
                    options={{
                        style: { paddingTop: 5 },
                        scrollEnabled:true,
                        nestedScrollEnabled:true,
                        showsHorizontalScrollIndicator:false,
                        showsVerticalScrollIndicator:false,
                    }}`

**Comment by Bound3R** [comment]
Hello, I solved it by doing the following:

this step brings the latest version of the repository directly as they have not updated the package for npm.
```shell
yarn add https://github.com/Eugnis/react-native-timeline-flatlist
```

here I add the property `isUsingFlatlist` that disables the flatlist and this allows to use it inside a scrollview
```javascript
import Timeline from "react-native-timeline-flatlist";

<Timeline
  data={this.data}
  isUsingFlatlist={false}
/>
```
With this I can now enjoy using this component within my views without any problems 😎 .
