### ISSUE TITLE
innerCircle size 

### ISSUE THREAD

**Issue by ramisalem** [Eugnis/react-native-timeline-flatlist#15]
Hello Thanks very much for such an awsome library 
I have a dot  innercircle  and the  circle size is set to 35   How could I resize innercircle which is the dot ? 
![Screen Shot 1441-08-03 at 4 44 10 PM](https://user-images.githubusercontent.com/25037017/77750649-30fd0300-704a-11ea-81bc-6030a8f64e52.png)

**Comment by Eugnis** [comment]
Hi. You can set custom dot size by passing `dotSize` prop to Timeline (update package to 0.7.1+ to use it)

**Comment by ramisalem** [comment]
Hi,Thank you very much
