### ISSUE TITLE
cannot customize paddingTop and paddinBottom applied by styles.detail

### ISSUE THREAD

**Issue by eightshone** [Eugnis/react-native-timeline-flatlist#19]
I need to align the circles to the titles, and currently there is no option to do that.
What I have currently:
![image](https://user-images.githubusercontent.com/36240779/78379836-e68c0100-75ca-11ea-8369-a0a4f86af4b5.png)
What I want to achieve:
![image](https://user-images.githubusercontent.com/36240779/78379878-f7d50d80-75ca-11ea-9f97-5f17f93af714.png)
I went through the code and figured out where the option should take place and I am working on a fix. I'll make a pull request shortly after this.

**Comment by luckdev01** [comment]
@eightshone Could you give me an example code for this fix?

**Comment by eightshone** [comment]
> @eightshone Could you give me an example code for this fix?

@luckdev01 hello there, as long as I remember (it has been over 3 years now) this was fixed in my pull request and it was merged already so theoretically this issue shouldn't exist anymore
