### ISSUE TITLE
Icon Props not working

### ISSUE THREAD

**Issue by abhishekgargx** [Eugnis/react-native-timeline-flatlist#2]
Trying to use icon prop but not working, but found dot prop is working.

**Comment by ahmad6242** [comment]
@Abhishekgarg727 did you find any solution to this ?

**Comment by claysol-pardeep** [comment]
it's not working for me too.

**Comment by SnehalAgrawal** [comment]
+1

**Comment by Eugnis** [comment]
Thanks, updated with fix for icons. Please check new version
