### ISSUE TITLE
How to scroll to the bottom on load?

### ISSUE THREAD

**Issue by fortydegrees** [Eugnis/react-native-timeline-flatlist#24]
not sure how to deleted comments, but you can just do it by putting initialScrollIndex: (last item) in the options={{}}

this wasn't working for me as stupidly had <Timeline> inside a <ScrollView>

**Comment by goxr3plus** [comment]
@fortydegrees  What actually you did :) ? Can you post some code please .

**Comment by goxr3plus** [comment]
I am trying to do the same thing , but actually scroll for example on item let's say `5`
