### ISSUE TITLE
Timeline not rendered

### ISSUE THREAD

**Issue by Manfrin92** [Eugnis/react-native-timeline-flatlist#27]
Hello,
I'm trying a simple example, but I noticed that when I use the Timeline component inside two consecutives Views Timeline doesn't get rendered. I don't know if I'm doing something wrong but the reason why I'm using those Views is for me to adjust the elements in the screen.

`<View style={{ flex: 1 }}>
      <View style={{ paddingTop: 12 }}>
        <View
          style={{ width: '100%', height: 150, backgroundColor: 'green' }}
        />
      </View>

      <View style={{ paddingTop: 20, paddingBottom: 32 }}>
        <View style={{ width: '100%', height: 150, backgroundColor: 'red' }} />
      </View>
 
      <View>
        <Timeline
          data={staticData}
          showTime={false}
          lineColor="#C4C4C4"
          innerCircle="icon"
          style={{ backgroundColor: 'yellow' }}
        />
      </View>

      <View style={{ paddingTop: 10 }}>
        <View style={{ width: '100%', height: 80, backgroundColor: 'blue' }} />
      </View>
    </View>`

If I remove these <View> around <Timeline> it gets rendered, Am I doing something wrong?

Thanks.

**Comment by Eugnis** [comment]
Looks like inner view with timeline have 0 height here and won't show up. You can add `style={{ flex: 1 }}` to View that wraps timeline like that
`...
<View style={{ flex: 1 }}>
    <Timeline
      data={staticData}
      showTime={false}
      lineColor="#C4C4C4"
      innerCircle="icon"
      style={{ backgroundColor: 'yellow' }}
    />
  </View>
...`
