### ISSUE TITLE
ListView is deprecated and will be removed in a future release warning.

### ISSUE THREAD

**Issue by ramonvictorn** [Eugnis/react-native-timeline-flatlist#28]
Changes ListView to the substitute [FlatList](https://reactnative.dev/blog/2017/03/13/better-list-views.html)
On Codes like this: 
![render_warning](https://user-images.githubusercontent.com/33635847/85781342-f57edd00-b6fb-11ea-91ee-b1ffeba94b55.png)

**Comment by Eugnis** [comment]
Seems you're using another package - [react-native-timeline-listview](https://github.com/thegamenicorus/react-native-timeline-listview). And [react-native-timeline-flatlist](https://github.com/Eugnis/react-native-timeline-flatlist) is this package, where listview replaced with flatlist
