### ISSUE TITLE
timeContainerStyle

### ISSUE THREAD

**Issue by RicardoBrito1938** [Eugnis/react-native-timeline-flatlist#34]
Hello team, i would like to move the timeContainerStyle to the same side than description events, is that possible?

**Comment by lissau** [comment]
Of course it is possible. But I'm sure the team would like you to argument as to why they should spend their time doing that. What's the benefit?

**Comment by RicardoBrito1938** [comment]
Indeed there where no benefit for that, i am closing the issue, and i would like to thank you for the support
